### PR TITLE
Streamlined a bit

### PR DESCRIPTION
**Pull request by SamBenson**
Removed the need for jQuery with a vanilla JS version, removed the
archive as contributors should zip it themselves and minified what
we’ve got so far.

### CODE REVIEW

**Comment by lwangenheim** [comment]
Awesome, thanks, it was a very quick app thrown together. I'll take a look at the PR over lunch and merge it up.

**Comment by slayyyyer** [comment]
`head = document.head || document.getElementsByTagName('head')[0]`
Shouldn't document.head just work in Chrome.

**Comment by SamBenson** [comment]
Yep, just tested it - works perfectly.

Good spot! :D

**Comment by lwangenheim** [comment]
*sorry for the extreme delay on this... reopened and merged. I really appreciate the help, today was one of those 'we live in the future' sort of days as someone I don't know can assist from across the pond with code I wrote less than a day ago.

**Comment by SamBenson** [comment]
All good, Lee. I actually closed this one as I've started working on a new
vote bar. I'm currently trying to find a way to grab the upvotes/downvotes
before they're available in the DOM.

**Comment by lwangenheim** [comment]
I was looking at that as well, It looks like they're in the 'stats' modal when you click 's'. Also a few people mentioned that the popup heart when you favorite by hitting '0' is still red, I looked at that and it's actually using a sprite image which appears to still have the green heart on it: http://s.imgur.com/images/site-sprite.png?1424368875, sadly I haven't had much spare time in the last few days to touch this, but I plan on poking around with it over the weekend.

**Comment by SamBenson** [comment]
OK, that's cool - I'll sort the image this weekend.

As for the stats - they're there but get loaded in via React once the modal
is opened. I haven't managed to find a way to get them without first
opening said modal so I've hit a bit of a brick wall. The HTML and CSS is
done for it though so I'll add that to a new branch so we can work on it
together.

**Comment by lwangenheim** [comment]
I wonder if we could trigger the load on a background page attached to the extension and then bring them over to the DOM.

**Comment by SamBenson** [comment]
Sounds like a good idea, could work!

**Pull request merged**
